# Generated by Django 3.1.7 on 2021-04-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210414_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='student_connected',
        ),
        migrations.RemoveField(
            model_name='room',
            name='student_unread_msgs',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tutor_connected',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tutor_unread_msgs',
        ),
    ]
