# Generated by Django 3.2.4 on 2021-06-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='student_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='tutor_connected',
            field=models.BooleanField(default=False),
        ),
    ]
