# Generated by Django 3.2.4 on 2021-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210627_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='room',
            name='student_connected',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tutor_connected',
        ),
        migrations.AddField(
            model_name='message',
            name='student_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='tutor_read',
            field=models.BooleanField(default=False),
        ),
    ]
