FROM python:3.7
ENV PYTHONBUFFERED 1

WORKDIR /app
COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app

WORKDIR /api

CMD python manage.py runserver 0.0.0.0:8080