events {}
http {
    server {
        listen 8080;

        location /api/ {
            proxy_pass http://localhost:8000;
            proxy_set_header Host $http_host;
        }

        location / {
            proxy_pass http://localhost:5500;
        }

        location /static/ {
            proxy_pass http://localhost:8000/static/;
        }

        location /media/ {
            proxy_pass http://localhost:8000/media/;
        }
    }
}