# Generated by Django 3.1.3 on 2021-01-12 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reset',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 1, 42, 14, 508185, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
