# Generated by Django 3.1.3 on 2021-01-24 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210123_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 24, 7, 27, 54, 285530, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
