# Generated by Django 3.1.3 on 2020-12-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('time_start', models.TimeField(help_text='put the time of your session by the 24 hour clock (ex. 10:30am would be 10:30, 10:30pm would be 22:30, 7am would be 07:00)')),
                ('time_end', models.TimeField(help_text='put the time of your session by the 24 hour clock (ex. 10:30am would be 10:30, 10:30pm would be 22:30, 7am would be 07:00)')),
                ('duration', models.DurationField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
                ('call_url', models.CharField(blank=True, max_length=30)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('accessable', models.BooleanField(default=False)),
                ('student_paid', models.BooleanField(default=False)),
                ('tutor_paid', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_available', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('tutor_emailed', models.BooleanField(default=False)),
                ('student_emailed', models.BooleanField(default=False)),
                ('parent_emailed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tutor')),
            ],
        ),
    ]
