# Generated by Django 3.2.7 on 2022-09-11 07:13

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.operations
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('session', '0001_initial'), ('session', '0002_session_canceled'), ('session', '0003_auto_20210405_1554'), ('session', '0004_auto_20210412_2027'), ('session', '0005_auto_20210412_2028'), ('session', '0006_auto_20210412_2031'), ('session', '0007_session_subjects'), ('session', '0008_session_refund_description'), ('session', '0009_auto_20210623_1420'), ('session', '0010_auto_20210625_2341'), ('session', '0011_session_student_joined'), ('session', '0012_seminar'), ('session', '0013_seminar_finished_seminar_started'), ('session', '0014_seminar_free_seminar_payment_id_seminar_price'), ('session', '0015_remove_seminar_payment_id_seminar_payment_ids'), ('session', '0016_rename_finished_seminar_active_remove_seminar_date_and_more'), ('session', '0017_remove_seminar_completed_remove_seminar_tutor_paid_and_more')]

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('register', '0014_auto_20211216_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('duration', models.DurationField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('free', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('call_url', models.CharField(blank=True, max_length=30)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('student_paid', models.BooleanField(default=False)),
                ('tutor_paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tutor')),
                ('canceled', models.BooleanField(default=False)),
                ('student_pk', models.IntegerField(default=69)),
                ('tutor_pk', models.IntegerField(default=42)),
                ('subjects', models.CharField(blank=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_joined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_pk', models.IntegerField()),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('duration', models.DurationField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('subjects', models.CharField(blank=True, max_length=64)),
                ('call_url', models.CharField(blank=True, max_length=30)),
                ('students', models.ManyToManyField(to='register.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tutor')),
                ('finished', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        django.contrib.postgres.operations.HStoreExtension(
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='payment_id',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='finished',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='started',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='students',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='time_start',
        ),
        migrations.AddField(
            model_name='seminar',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=[datetime.datetime(2022, 9, 4, 21, 11, 59, 11254, tzinfo=utc), datetime.datetime(2022, 9, 4, 21, 11, 59, 16828, tzinfo=utc)], size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.seminar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
        migrations.AddField(
            model_name='seminar',
            name='payouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='sessions_completed',
            field=models.IntegerField(default=0),
        ),
    ]
