# Generated by Django 3.1.7 on 2021-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20210412_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
