# Generated by Django 3.1.7 on 2021-04-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20210412_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
