# Generated by Django 3.1.7 on 2021-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20210412_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subjects',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
