# Generated by Django 3.2.4 on 2021-06-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_session_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='refund_description',
            field=models.TextField(blank=True),
        ),
    ]
