# Generated by Django 3.2.4 on 2021-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_session_refund_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='parent_emailed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='refund_available',
        ),
        migrations.RemoveField(
            model_name='session',
            name='refund_description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='refund_requested',
        ),
        migrations.RemoveField(
            model_name='session',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='session',
            name='student_emailed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tutor_emailed',
        ),
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
