# Generated by Django 3.2.4 on 2021-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20210623_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='accessable',
        ),
        migrations.AddField(
            model_name='session',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
