# Generated by Django 3.2.4 on 2021-07-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20210625_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student_joined',
            field=models.BooleanField(default=False),
        ),
    ]
