# Generated by Django 4.0.6 on 2022-07-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20211216_1953'),
        ('session', '0011_session_student_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_pk', models.IntegerField()),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('duration', models.DurationField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('subjects', models.CharField(blank=True, max_length=64)),
                ('call_url', models.CharField(blank=True, max_length=30)),
                ('students', models.ManyToManyField(to='register.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tutor')),
            ],
        ),
    ]
