# Generated by Django 4.0.6 on 2022-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminar',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
