# Generated by Django 4.0.6 on 2022-07-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_seminar_finished_seminar_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminar',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
