# Generated by Django 4.0.6 on 2022-07-16 00:45

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_seminar_free_seminar_payment_id_seminar_price'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='seminar',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='seminar',
            name='payment_ids',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
