# Generated by Django 4.0.6 on 2022-09-04 21:11

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20211216_1953'),
        ('session', '0015_remove_seminar_payment_id_seminar_payment_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='finished',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='payment_ids',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='started',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='students',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='time_start',
        ),
        migrations.AddField(
            model_name='seminar',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=[datetime.datetime(2022, 9, 4, 21, 11, 59, 11254, tzinfo=utc), datetime.datetime(2022, 9, 4, 21, 11, 59, 16828, tzinfo=utc)], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='tutor_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StudentSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.seminar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
    ]
