# Generated by Django 4.0.6 on 2022-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_rename_finished_seminar_active_remove_seminar_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='tutor_paid',
        ),
        migrations.AddField(
            model_name='seminar',
            name='payouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='sessions_completed',
            field=models.IntegerField(default=0),
        ),
    ]
