# Generated by Django 3.1.3 on 2020-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
