# Generated by Django 3.1.7 on 2021-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student_pk',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_pk',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
