# Generated by Django 3.2.6 on 2021-12-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='bug',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
