events {}
http {
    server {
        listen 5000;

        location /api/ {
            proxy_pass http://localhost:8000;
            proxy_set_header Host $http_host;
        }

        location / {
            proxy_pass http://localhost:3000;
        }

        location /static/ {
            proxy_pass http://localhost:8000/static/;
        }

        location /media/ {
            proxy_pass http://localhost:8000/media/;
        }

        location /api/ws/ {
            proxy_pass http://localhost:8000/api/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}