# Generated by Django 3.1.3 on 2020-12-05 20:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email_authenticated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(default='person.png', upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('qualifications', models.TextField(max_length=1000)),
                ('what_you_teach', models.TextField(help_text='Give us a class description.', max_length=1000)),
                ('subjects', models.CharField(max_length=100)),
                ('birth_date', models.DateField(help_text='YYYY-MM-DD')),
                ('bio', models.TextField(help_text='Tell potential students about yourself', max_length=1000)),
                ('rates', models.DecimalField(decimal_places=2, help_text='How much will you charge per hour?', max_digits=10)),
                ('occupation', models.CharField(max_length=100)),
                ('linkedIn', models.URLField(blank=True, help_text='You may optionally put your LinkedIn profile URL.  Make sure to put it in the format of https://www.linkedin.com/in/[rest of url]')),
                ('verified', models.BooleanField(default=False)),
                ('prof_exp', models.IntegerField()),
                ('teach_exp', models.IntegerField()),
                ('education', models.CharField(choices=[('High School', 'High School'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree'), ('Ph.D.', 'Ph.D.')], max_length=16)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=17)),
                ('tutor_type', models.CharField(max_length=50)),
                ('availability', models.CharField(help_text='Please explain your availability times.', max_length=500)),
                ('num_classes', models.IntegerField()),
                ('average_reviews', models.FloatField()),
                ('num_reviews', models.IntegerField()),
                ('free_tutoring_given', models.DurationField(default=datetime.timedelta(0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(help_text='YYYY-MM-DD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('stars', models.IntegerField(choices=[(0, '0 stars'), (1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tutor')),
            ],
        ),
    ]
