# Generated by Django 3.1.3 on 2021-01-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reset',
            field=models.DateTimeField(null=True),
        ),
    ]
