# Generated by Django 3.1.3 on 2021-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210123_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reset',
            field=models.DateTimeField(null=True),
        ),
    ]
