# Generated by Django 3.1.3 on 2021-02-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210206_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_authenticated',
        ),
    ]
