# Generated by Django 3.1.7 on 2021-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_user_email_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tutor_id',
            field=models.IntegerField(null=True),
        ),
    ]
