# Generated by Django 3.1.7 on 2021-03-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210322_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='average_reviews',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='num_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
