# Generated by Django 3.1.7 on 2021-04-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210322_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='student_pk',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tutor_id',
            new_name='tutor_pk',
        ),
    ]
