# Generated by Django 3.1.7 on 2021-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20210405_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tutor_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
