# Generated by Django 3.2.4 on 2021-06-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='availability',
            field=models.CharField(blank=True, help_text='Please explain your availability times.', max_length=500),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
