# Generated by Django 3.2.6 on 2021-12-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20210622_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='availability',
            field=models.CharField(blank=True, help_text='Please explain your availability times.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell potential students about yourself', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='prof_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='qualifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='teach_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='what_you_teach',
            field=models.TextField(blank=True, help_text='Give us a class description.', max_length=1000, null=True),
        ),
    ]
